ALTER TABLE agent_runs
ADD COLUMN IF NOT EXISTS user_prompt_tokens INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS system_prompt_tokens INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS context_tokens INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS tool_result_tokens INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS memory_tokens INTEGER NOT NULL DEFAULT 0;
